# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_fnd/ip/Mblaze_fnd_axi_gpio_0_0/Mblaze_fnd_axi_gpio_0_0.xci
# IP: The module: 'Mblaze_fnd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_fnd/ip/Mblaze_fnd_axi_gpio_0_0/Mblaze_fnd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_fnd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_fnd/ip/Mblaze_fnd_axi_gpio_0_0/Mblaze_fnd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_fnd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_fnd/ip/Mblaze_fnd_axi_gpio_0_0/Mblaze_fnd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_fnd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_fnd/ip/Mblaze_fnd_axi_gpio_0_0/Mblaze_fnd_axi_gpio_0_0.xci
# IP: The module: 'Mblaze_fnd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_fnd/ip/Mblaze_fnd_axi_gpio_0_0/Mblaze_fnd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_fnd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_fnd/ip/Mblaze_fnd_axi_gpio_0_0/Mblaze_fnd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_fnd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_fnd/ip/Mblaze_fnd_axi_gpio_0_0/Mblaze_fnd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_fnd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
