# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hama5/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Micro_blaze_iic_v0/ip/Micro_blaze_iic_v0_lmb_bram_0/Micro_blaze_iic_v0_lmb_bram_0.xci
# IP: The module: 'Micro_blaze_iic_v0_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hama5/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Micro_blaze_iic_v0/ip/Micro_blaze_iic_v0_lmb_bram_0/Micro_blaze_iic_v0_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Micro_blaze_iic_v0_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/hama5/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Micro_blaze_iic_v0/ip/Micro_blaze_iic_v0_lmb_bram_0/Micro_blaze_iic_v0_lmb_bram_0.xci
# IP: The module: 'Micro_blaze_iic_v0_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hama5/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Micro_blaze_iic_v0/ip/Micro_blaze_iic_v0_lmb_bram_0/Micro_blaze_iic_v0_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Micro_blaze_iic_v0_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
