# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_xbar_0/micro_blaze_button_xbar_0.xci
# IP: The module: 'micro_blaze_button_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_xbar_0/micro_blaze_button_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_blaze_button_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_xbar_0/micro_blaze_button_xbar_0.xci
# IP: The module: 'micro_blaze_button_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/SG_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/micro_blaze_button/ip/micro_blaze_button_xbar_0/micro_blaze_button_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_blaze_button_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
