# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/소스파일/Basys-3-Master.xdc

# Block Designs: bd/Remo_cuckoo/Remo_cuckoo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo || ORIG_REF_NAME==Remo_cuckoo} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_myip_pwm_0_0/Remo_cuckoo_myip_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_myip_pwm_0_0 || ORIG_REF_NAME==Remo_cuckoo_myip_pwm_0_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_clk_wiz_0_0/Remo_cuckoo_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_clk_wiz_0_0 || ORIG_REF_NAME==Remo_cuckoo_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_microblaze_0_0/Remo_cuckoo_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_microblaze_0_0 || ORIG_REF_NAME==Remo_cuckoo_microblaze_0_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_dlmb_v10_0/Remo_cuckoo_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_dlmb_v10_0 || ORIG_REF_NAME==Remo_cuckoo_dlmb_v10_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_ilmb_v10_0/Remo_cuckoo_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_ilmb_v10_0 || ORIG_REF_NAME==Remo_cuckoo_ilmb_v10_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_dlmb_bram_if_cntlr_0/Remo_cuckoo_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Remo_cuckoo_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_ilmb_bram_if_cntlr_0/Remo_cuckoo_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Remo_cuckoo_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_lmb_bram_0/Remo_cuckoo_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_lmb_bram_0 || ORIG_REF_NAME==Remo_cuckoo_lmb_bram_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_xbar_0/Remo_cuckoo_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_xbar_0 || ORIG_REF_NAME==Remo_cuckoo_xbar_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_microblaze_0_axi_periph_0/Remo_cuckoo_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Remo_cuckoo_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_microblaze_0_axi_intc_0/Remo_cuckoo_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Remo_cuckoo_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_microblaze_0_xlconcat_0/Remo_cuckoo_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Remo_cuckoo_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_mdm_1_0/Remo_cuckoo_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_mdm_1_0 || ORIG_REF_NAME==Remo_cuckoo_mdm_1_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_rst_clk_wiz_0_100M_0/Remo_cuckoo_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Remo_cuckoo_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_uartlite_0_0/Remo_cuckoo_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_axi_uartlite_0_0 || ORIG_REF_NAME==Remo_cuckoo_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_iic_0_0/Remo_cuckoo_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_axi_iic_0_0 || ORIG_REF_NAME==Remo_cuckoo_axi_iic_0_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_gpio_0_0/Remo_cuckoo_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_axi_gpio_0_0 || ORIG_REF_NAME==Remo_cuckoo_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_myip_bluetooth_0_2/Remo_cuckoo_myip_bluetooth_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_myip_bluetooth_0_2 || ORIG_REF_NAME==Remo_cuckoo_myip_bluetooth_0_2} -quiet] -quiet

# IP: bd/Remo_cuckoo/ip/Remo_cuckoo_myip_clock_timer_0_5/Remo_cuckoo_myip_clock_timer_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Remo_cuckoo_myip_clock_timer_0_5 || ORIG_REF_NAME==Remo_cuckoo_myip_clock_timer_0_5} -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_clk_wiz_0_0/Remo_cuckoo_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_clk_wiz_0_0 || ORIG_REF_NAME==Remo_cuckoo_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_clk_wiz_0_0/Remo_cuckoo_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_clk_wiz_0_0 || ORIG_REF_NAME==Remo_cuckoo_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_clk_wiz_0_0/Remo_cuckoo_clk_wiz_0_0_ooc.xdc

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_microblaze_0_0/Remo_cuckoo_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_microblaze_0_0 || ORIG_REF_NAME==Remo_cuckoo_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_microblaze_0_0/Remo_cuckoo_microblaze_0_0_ooc_debug.xdc

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_dlmb_v10_0/Remo_cuckoo_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_dlmb_v10_0 || ORIG_REF_NAME==Remo_cuckoo_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_ilmb_v10_0/Remo_cuckoo_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_ilmb_v10_0 || ORIG_REF_NAME==Remo_cuckoo_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_lmb_bram_0/Remo_cuckoo_lmb_bram_0_ooc.xdc

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_microblaze_0_axi_intc_0/Remo_cuckoo_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Remo_cuckoo_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_microblaze_0_axi_intc_0/Remo_cuckoo_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Remo_cuckoo_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_microblaze_0_axi_intc_0/Remo_cuckoo_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_mdm_1_0/Remo_cuckoo_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_mdm_1_0 || ORIG_REF_NAME==Remo_cuckoo_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_mdm_1_0/Remo_cuckoo_mdm_1_0_ooc_trace.xdc

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_rst_clk_wiz_0_100M_0/Remo_cuckoo_rst_clk_wiz_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Remo_cuckoo_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_rst_clk_wiz_0_100M_0/Remo_cuckoo_rst_clk_wiz_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Remo_cuckoo_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_uartlite_0_0/Remo_cuckoo_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_axi_uartlite_0_0 || ORIG_REF_NAME==Remo_cuckoo_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_uartlite_0_0/Remo_cuckoo_axi_uartlite_0_0_ooc.xdc

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_uartlite_0_0/Remo_cuckoo_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_axi_uartlite_0_0 || ORIG_REF_NAME==Remo_cuckoo_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_iic_0_0/Remo_cuckoo_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_axi_iic_0_0 || ORIG_REF_NAME==Remo_cuckoo_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_iic_0_0/Remo_cuckoo_axi_iic_0_0_ooc.xdc

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_gpio_0_0/Remo_cuckoo_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_axi_gpio_0_0 || ORIG_REF_NAME==Remo_cuckoo_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_gpio_0_0/Remo_cuckoo_axi_gpio_0_0_ooc.xdc

# XDC: bd/Remo_cuckoo/ip/Remo_cuckoo_axi_gpio_0_0/Remo_cuckoo_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Remo_cuckoo_axi_gpio_0_0 || ORIG_REF_NAME==Remo_cuckoo_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Remo_cuckoo/Remo_cuckoo_ooc.xdc
