# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/SUJIN/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_btn_intr/ip/Mblaze_btn_intr_microblaze_0_axi_intc_0/Mblaze_btn_intr_microblaze_0_axi_intc_0.xci
# IP: The module: 'Mblaze_btn_intr_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SUJIN/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_btn_intr/ip/Mblaze_btn_intr_microblaze_0_axi_intc_0/Mblaze_btn_intr_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_btn_intr_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SUJIN/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_btn_intr/ip/Mblaze_btn_intr_microblaze_0_axi_intc_0/Mblaze_btn_intr_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_btn_intr_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SUJIN/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_btn_intr/ip/Mblaze_btn_intr_microblaze_0_axi_intc_0/Mblaze_btn_intr_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_btn_intr_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/SUJIN/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_btn_intr/ip/Mblaze_btn_intr_microblaze_0_axi_intc_0/Mblaze_btn_intr_microblaze_0_axi_intc_0.xci
# IP: The module: 'Mblaze_btn_intr_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SUJIN/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_btn_intr/ip/Mblaze_btn_intr_microblaze_0_axi_intc_0/Mblaze_btn_intr_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_btn_intr_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SUJIN/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_btn_intr/ip/Mblaze_btn_intr_microblaze_0_axi_intc_0/Mblaze_btn_intr_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_btn_intr_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SUJIN/Desktop/sg_workspace/SoC_soc_24/SoC_soc_24.srcs/sources_1/bd/Mblaze_btn_intr/ip/Mblaze_btn_intr_microblaze_0_axi_intc_0/Mblaze_btn_intr_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mblaze_btn_intr_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
